#!/bin/bash
while IFS='' read -r line || [[ -n "$line" ]]; do
    val=$(./next_prog $line)
    if [[ $val =~ .*Pending.* ]]; then
	    echo "$line is pending" 
    else
	    echo "$line is fine"
    fi
done < "$1"
